# This file is used as an example to run with docker-compose-prom-only.yml for demo purposes.
# Update it with the relevant targets for your cluster
global:
 scrape_interval: 10s
 evaluation_interval: 10s
scrape_configs:
 - job_name: 'kafka'
   static_configs:
    - targets:
      - localhost:8081
      - localhost:8082
      - localhost:8083