global:
 scrape_interval: 10s
 evaluation_interval: 10s
scrape_configs:
 - job_name: 'kafka'
   static_configs:
    - targets:
    # Update the list below with your Kafka listener and the port you set when you added the JMX exporter
      - kafka1:8081
      - kafka2:8081
      - kafka3:8081
      - kafka4:8081
      - kafka5:8081