name: CI

on:
  push:
    branches: 
    - main
    - dev
  pull_request:
    branches: 
    - main
    - dev
    

jobs:
  build:

    runs-on: macos-latest
    environment: dev

    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: create env file
      run: |
        touch .env
        echo KAKFA_BROKER=${{ secrets.BROKER }} >> .env
        echo PROMETHEUS_URL=${{ secrets.PROMETHEUS_URL }} >> .env
        cat .env
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --if-present
